-- 카테고리 데이터 (ID: 1~8)
INSERT INTO CATEGORY (CATEGORY_ID, CATEGORY_NAME, CREATED_AT, UPDATED_AT) VALUES (1, '상의', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO CATEGORY (CATEGORY_ID, CATEGORY_NAME, CREATED_AT, UPDATED_AT) VALUES (2, '아우터', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO CATEGORY (CATEGORY_ID, CATEGORY_NAME, CREATED_AT, UPDATED_AT) VALUES (3, '바지', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO CATEGORY (CATEGORY_ID, CATEGORY_NAME, CREATED_AT, UPDATED_AT) VALUES (4, '스니커즈', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO CATEGORY (CATEGORY_ID, CATEGORY_NAME, CREATED_AT, UPDATED_AT) VALUES (5, '가방', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO CATEGORY (CATEGORY_ID, CATEGORY_NAME, CREATED_AT, UPDATED_AT) VALUES (6, '모자', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO CATEGORY (CATEGORY_ID, CATEGORY_NAME, CREATED_AT, UPDATED_AT) VALUES (7, '양말', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO CATEGORY (CATEGORY_ID, CATEGORY_NAME, CREATED_AT, UPDATED_AT) VALUES (8, '액세서리', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

-- 브랜드 데이터 (ID: 1~9)
INSERT INTO BRAND (BRAND_ID, BRAND_NAME, CREATED_AT, UPDATED_AT) VALUES (10000, 'A', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO BRAND (BRAND_ID, BRAND_NAME, CREATED_AT, UPDATED_AT) VALUES (20000, 'B', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO BRAND (BRAND_ID, BRAND_NAME, CREATED_AT, UPDATED_AT) VALUES (30000, 'C', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO BRAND (BRAND_ID, BRAND_NAME, CREATED_AT, UPDATED_AT) VALUES (40000, 'D', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO BRAND (BRAND_ID, BRAND_NAME, CREATED_AT, UPDATED_AT) VALUES (50000, 'E', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO BRAND (BRAND_ID, BRAND_NAME, CREATED_AT, UPDATED_AT) VALUES (60000, 'F', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO BRAND (BRAND_ID, BRAND_NAME, CREATED_AT, UPDATED_AT) VALUES (70000, 'G', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO BRAND (BRAND_ID, BRAND_NAME, CREATED_AT, UPDATED_AT) VALUES (80000, 'H', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO BRAND (BRAND_ID, BRAND_NAME, CREATED_AT, UPDATED_AT) VALUES (90000, 'I', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

-- 상품 데이터
-- 브랜드 A (ID=1): {11200, 5500, 4200, 9000, 2000, 1700, 1800, 2300}
INSERT INTO PRODUCT (BRAND_ID, CATEGORY_ID, PRICE, CREATED_AT, UPDATED_AT) VALUES (10000, 1, 11200, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO PRODUCT (BRAND_ID, CATEGORY_ID, PRICE, CREATED_AT, UPDATED_AT) VALUES (10000, 2, 5500, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO PRODUCT (BRAND_ID, CATEGORY_ID, PRICE, CREATED_AT, UPDATED_AT) VALUES (10000, 3, 4200, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO PRODUCT (BRAND_ID, CATEGORY_ID, PRICE, CREATED_AT, UPDATED_AT) VALUES (10000, 4, 9000, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO PRODUCT (BRAND_ID, CATEGORY_ID, PRICE, CREATED_AT, UPDATED_AT) VALUES (10000, 5, 2000, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO PRODUCT (BRAND_ID, CATEGORY_ID, PRICE, CREATED_AT, UPDATED_AT) VALUES (10000, 6, 1700, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO PRODUCT (BRAND_ID, CATEGORY_ID, PRICE, CREATED_AT, UPDATED_AT) VALUES (10000, 7, 1800, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO PRODUCT (BRAND_ID, CATEGORY_ID, PRICE, CREATED_AT, UPDATED_AT) VALUES (10000, 8, 2300, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

-- 브랜드 B (ID=2): {10500, 5900, 3800, 9100, 2100, 2000, 2000, 2200}
INSERT INTO PRODUCT (BRAND_ID, CATEGORY_ID, PRICE, CREATED_AT, UPDATED_AT) VALUES (20000, 1, 10500, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO PRODUCT (BRAND_ID, CATEGORY_ID, PRICE, CREATED_AT, UPDATED_AT) VALUES (20000, 2, 5900, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO PRODUCT (BRAND_ID, CATEGORY_ID, PRICE, CREATED_AT, UPDATED_AT) VALUES (20000, 3, 3800, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO PRODUCT (BRAND_ID, CATEGORY_ID, PRICE, CREATED_AT, UPDATED_AT) VALUES (20000, 4, 9100, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO PRODUCT (BRAND_ID, CATEGORY_ID, PRICE, CREATED_AT, UPDATED_AT) VALUES (20000, 5, 2100, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO PRODUCT (BRAND_ID, CATEGORY_ID, PRICE, CREATED_AT, UPDATED_AT) VALUES (20000, 6, 2000, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO PRODUCT (BRAND_ID, CATEGORY_ID, PRICE, CREATED_AT, UPDATED_AT) VALUES (20000, 7, 2000, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO PRODUCT (BRAND_ID, CATEGORY_ID, PRICE, CREATED_AT, UPDATED_AT) VALUES (20000, 8, 2200, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

-- 브랜드 C (ID=3): {10000, 6200, 3300, 9200, 2200, 1900, 2200, 2100}
INSERT INTO PRODUCT (BRAND_ID, CATEGORY_ID, PRICE, CREATED_AT, UPDATED_AT) VALUES (30000, 1, 10000, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO PRODUCT (BRAND_ID, CATEGORY_ID, PRICE, CREATED_AT, UPDATED_AT) VALUES (30000, 2, 6200, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO PRODUCT (BRAND_ID, CATEGORY_ID, PRICE, CREATED_AT, UPDATED_AT) VALUES (30000, 3, 3300, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO PRODUCT (BRAND_ID, CATEGORY_ID, PRICE, CREATED_AT, UPDATED_AT) VALUES (30000, 4, 9200, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO PRODUCT (BRAND_ID, CATEGORY_ID, PRICE, CREATED_AT, UPDATED_AT) VALUES (30000, 5, 2200, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO PRODUCT (BRAND_ID, CATEGORY_ID, PRICE, CREATED_AT, UPDATED_AT) VALUES (30000, 6, 1900, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO PRODUCT (BRAND_ID, CATEGORY_ID, PRICE, CREATED_AT, UPDATED_AT) VALUES (30000, 7, 2200, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO PRODUCT (BRAND_ID, CATEGORY_ID, PRICE, CREATED_AT, UPDATED_AT) VALUES (30000, 8, 2100, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

-- 브랜드 D (ID=4): {10100, 5100, 3000, 9500, 2500, 1500, 2400, 2000}
INSERT INTO PRODUCT (BRAND_ID, CATEGORY_ID, PRICE, CREATED_AT, UPDATED_AT) VALUES (40000, 1, 10100, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO PRODUCT (BRAND_ID, CATEGORY_ID, PRICE, CREATED_AT, UPDATED_AT) VALUES (40000, 2, 5100, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO PRODUCT (BRAND_ID, CATEGORY_ID, PRICE, CREATED_AT, UPDATED_AT) VALUES (40000, 3, 3000, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO PRODUCT (BRAND_ID, CATEGORY_ID, PRICE, CREATED_AT, UPDATED_AT) VALUES (40000, 4, 9500, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO PRODUCT (BRAND_ID, CATEGORY_ID, PRICE, CREATED_AT, UPDATED_AT) VALUES (40000, 5, 2500, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO PRODUCT (BRAND_ID, CATEGORY_ID, PRICE, CREATED_AT, UPDATED_AT) VALUES (40000, 6, 1500, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO PRODUCT (BRAND_ID, CATEGORY_ID, PRICE, CREATED_AT, UPDATED_AT) VALUES (40000, 7, 2400, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO PRODUCT (BRAND_ID, CATEGORY_ID, PRICE, CREATED_AT, UPDATED_AT) VALUES (40000, 8, 2000, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

-- 브랜드 E (ID=5): {10700, 5000, 3800, 9900, 2300, 1800, 2100, 2100}
INSERT INTO PRODUCT (BRAND_ID, CATEGORY_ID, PRICE, CREATED_AT, UPDATED_AT) VALUES (50000, 1, 10700, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO PRODUCT (BRAND_ID, CATEGORY_ID, PRICE, CREATED_AT, UPDATED_AT) VALUES (50000, 2, 5000, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO PRODUCT (BRAND_ID, CATEGORY_ID, PRICE, CREATED_AT, UPDATED_AT) VALUES (50000, 3, 3800, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO PRODUCT (BRAND_ID, CATEGORY_ID, PRICE, CREATED_AT, UPDATED_AT) VALUES (50000, 4, 9900, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO PRODUCT (BRAND_ID, CATEGORY_ID, PRICE, CREATED_AT, UPDATED_AT) VALUES (50000, 5, 2300, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO PRODUCT (BRAND_ID, CATEGORY_ID, PRICE, CREATED_AT, UPDATED_AT) VALUES (50000, 6, 1800, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO PRODUCT (BRAND_ID, CATEGORY_ID, PRICE, CREATED_AT, UPDATED_AT) VALUES (50000, 7, 2100, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO PRODUCT (BRAND_ID, CATEGORY_ID, PRICE, CREATED_AT, UPDATED_AT) VALUES (50000, 8, 2100, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

-- 브랜드 F (ID=6): {11200, 7200, 4000, 9300, 2100, 1600, 2300, 1900}
INSERT INTO PRODUCT (BRAND_ID, CATEGORY_ID, PRICE, CREATED_AT, UPDATED_AT) VALUES (60000, 1, 11200, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO PRODUCT (BRAND_ID, CATEGORY_ID, PRICE, CREATED_AT, UPDATED_AT) VALUES (60000, 2, 7200, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO PRODUCT (BRAND_ID, CATEGORY_ID, PRICE, CREATED_AT, UPDATED_AT) VALUES (60000, 3, 4000, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO PRODUCT (BRAND_ID, CATEGORY_ID, PRICE, CREATED_AT, UPDATED_AT) VALUES (60000, 4, 9300, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO PRODUCT (BRAND_ID, CATEGORY_ID, PRICE, CREATED_AT, UPDATED_AT) VALUES (60000, 5, 2100, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO PRODUCT (BRAND_ID, CATEGORY_ID, PRICE, CREATED_AT, UPDATED_AT) VALUES (60000, 6, 1600, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO PRODUCT (BRAND_ID, CATEGORY_ID, PRICE, CREATED_AT, UPDATED_AT) VALUES (60000, 7, 2300, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO PRODUCT (BRAND_ID, CATEGORY_ID, PRICE, CREATED_AT, UPDATED_AT) VALUES (60000, 8, 1900, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

-- 브랜드 G (ID=7): {10500, 5800, 3900, 9000, 2200, 1700, 2100, 2000}
INSERT INTO PRODUCT (BRAND_ID, CATEGORY_ID, PRICE, CREATED_AT, UPDATED_AT) VALUES (70000, 1, 10500, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO PRODUCT (BRAND_ID, CATEGORY_ID, PRICE, CREATED_AT, UPDATED_AT) VALUES (70000, 2, 5800, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO PRODUCT (BRAND_ID, CATEGORY_ID, PRICE, CREATED_AT, UPDATED_AT) VALUES (70000, 3, 3900, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO PRODUCT (BRAND_ID, CATEGORY_ID, PRICE, CREATED_AT, UPDATED_AT) VALUES (70000, 4, 9000, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO PRODUCT (BRAND_ID, CATEGORY_ID, PRICE, CREATED_AT, UPDATED_AT) VALUES (70000, 5, 2200, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO PRODUCT (BRAND_ID, CATEGORY_ID, PRICE, CREATED_AT, UPDATED_AT) VALUES (70000, 6, 1700, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO PRODUCT (BRAND_ID, CATEGORY_ID, PRICE, CREATED_AT, UPDATED_AT) VALUES (70000, 7, 2100, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO PRODUCT (BRAND_ID, CATEGORY_ID, PRICE, CREATED_AT, UPDATED_AT) VALUES (70000, 8, 2000, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

-- 브랜드 H (ID=8): {10800, 6300, 3100, 9700, 2100, 1600, 2000, 2000}
INSERT INTO PRODUCT (BRAND_ID, CATEGORY_ID, PRICE, CREATED_AT, UPDATED_AT) VALUES (80000, 1, 10800, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO PRODUCT (BRAND_ID, CATEGORY_ID, PRICE, CREATED_AT, UPDATED_AT) VALUES (80000, 2, 6300, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO PRODUCT (BRAND_ID, CATEGORY_ID, PRICE, CREATED_AT, UPDATED_AT) VALUES (80000, 3, 3100, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO PRODUCT (BRAND_ID, CATEGORY_ID, PRICE, CREATED_AT, UPDATED_AT) VALUES (80000, 4, 9700, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO PRODUCT (BRAND_ID, CATEGORY_ID, PRICE, CREATED_AT, UPDATED_AT) VALUES (80000, 5, 2100, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO PRODUCT (BRAND_ID, CATEGORY_ID, PRICE, CREATED_AT, UPDATED_AT) VALUES (80000, 6, 1600, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO PRODUCT (BRAND_ID, CATEGORY_ID, PRICE, CREATED_AT, UPDATED_AT) VALUES (80000, 7, 2000, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO PRODUCT (BRAND_ID, CATEGORY_ID, PRICE, CREATED_AT, UPDATED_AT) VALUES (80000, 8, 2000, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

-- 브랜드 I (ID=9): {11400, 6700, 3200, 9500, 2400, 1700, 1700, 2400}
INSERT INTO PRODUCT (BRAND_ID, CATEGORY_ID, PRICE, CREATED_AT, UPDATED_AT) VALUES (90000, 1, 11400, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO PRODUCT (BRAND_ID, CATEGORY_ID, PRICE, CREATED_AT, UPDATED_AT) VALUES (90000, 2, 6700, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO PRODUCT (BRAND_ID, CATEGORY_ID, PRICE, CREATED_AT, UPDATED_AT) VALUES (90000, 3, 3200, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO PRODUCT (BRAND_ID, CATEGORY_ID, PRICE, CREATED_AT, UPDATED_AT) VALUES (90000, 4, 9500, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO PRODUCT (BRAND_ID, CATEGORY_ID, PRICE, CREATED_AT, UPDATED_AT) VALUES (90000, 5, 2400, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO PRODUCT (BRAND_ID, CATEGORY_ID, PRICE, CREATED_AT, UPDATED_AT) VALUES (90000, 6, 1700, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO PRODUCT (BRAND_ID, CATEGORY_ID, PRICE, CREATED_AT, UPDATED_AT) VALUES (90000, 7, 1700, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO PRODUCT (BRAND_ID, CATEGORY_ID, PRICE, CREATED_AT, UPDATED_AT) VALUES (90000, 8, 2400, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
